In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype=int)
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
zeros_arr=np.zeros((3,3),dtype=int)

print(zeros_arr)
ones_arr=np.ones((2,2),dtype=int)
print(ones_arr)

arange_arr=np.arange(5)
print(arange_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]
[0 1 2 3 4]


In [ ]:
import numpy as np
#Array manuculation
#arr=np.array([1,2,3,4,5],dtype=int)
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)



[[1]
 [2]
 [3]
 [4]
 [5]]
[3]


In [ ]:
#transpose of the array

a=np.array([11,12,13,14,15,16,18,19])
b=a.T
print(b)

[11 12 13 14 15 16 18 19]


In [ ]:
#.split function
b=np.split(a,4)
print(b)

[array([11, 12]), array([13, 14]), array([15, 16]), array([18, 19])]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)

d=np.linalg.eig(c)
print(d)

[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
data =np.loadtxt("/content/drive/MyDrive/DataSet/Dap.txt",dtype=int)
d=np.savetxt("/content/Dap.txt",data)
print(d)
print(data)

None
[[1 2 3 4 5 6]
 [7 8 9 4 9 2]]


In [ ]:
arr=np.arange(0,100,5)
print(arr)

data=np.savetxt("/content/arr.txt",arr)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:

a=np.random.rand()

print(a)

0.9437162605912024


In [ ]:
b=np.random.randint(0,100)
print(b)
print(type(a))

9
<class 'float'>


In [ ]:
c=np.array([2,2])
print(c)




[2 2]


In [ ]:
d=np.linspace(0.8,2,5)
print(d)

b=np.arange(24).reshape(3,2,4)
print(b)



[0.8 1.1 1.4 1.7 2. ]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [ ]:
f=np.array([[99,100],[101,102]])
h=np.array([[1,2],[3,4]])
print(f/h)

print(f*h)
print(f%h)

print(np.dot(f,h))
print(f@(h))


[[99.         50.        ]
 [33.66666667 25.5       ]]
[[ 99 200]
 [303 408]]
[[0 0]
 [2 2]]
[[399 598]
 [407 610]]
[[399 598]
 [407 610]]


In [ ]:
from numpy import random

a=np.array([[1,2,3,4],[5,6,7,8]])

print(a.sum())
print(a.sum(axis=0))


b=np.array([[2,3,5,6,7,8]])

print(b.cumsum(axis=1))

print(b.resize(3,2))

print(b.shape)

36
[ 6  8 10 12]
[[ 2  5 10 16 23 31]]
None
(3, 2)


In [ ]:
a=np.array([[2,3,5,6,7,8]])

print(a.resize(2,3))

b=np.array([[9,10,11,12,13,14]])
print(b.resize(2,3))

print(np.vstack((a,b)))


None
None
[[ 2  3  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
a1=np.eye(4)
print(a1)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
x=[1,2,3]
b1=np.array(x)
print(b1)
print(type(b1))


[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))


10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [ ]:
a=np.array([1.1,1.2,1.3])
print(np.rint(a))

b=np.array([15,55,65,89,90])
c=np.array([45,85,75,86,70])
print(np.true_divide(b,c))





[1. 1. 1.]
[0.33333333 0.64705882 0.86666667 1.03488372 1.28571429]


In [ ]:
g=np.array([[15,55],[85,55]])
h=np.array([[45,85],[15,10]])
print(np.union1d(g,h))

print(np.intersect1d(g,h))

print(np.setdiff1d(g,h))

a=np.array([[10,21,50,2,25,25]])
b=np.array([[10,21,50,2,25,25]])
c=np.divmod(a,b)
print(c)

print(np.divide(a,b))

print(np.multiply(a,b))




[10 15 45 55 85]
[15 85]
[55]
(array([[1, 1, 1, 1, 1, 1]]), array([[0, 0, 0, 0, 0, 0]]))
[[1. 1. 1. 1. 1. 1.]]
[[ 100  441 2500    4  625  625]]


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)
print("  ")
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)
print("   ")
x=random.binomial(n=12,p=0.5,size=10)
print(x)
print("   ")
x=random.choice([3,5])
print(x)
print("   ")
x=random.choice([3,5],p=[.5,.5],size=(3,5))
print(x)

[[-1.59203594  0.14134687 -0.0585691 ]
 [ 0.50338226 -0.22762238 -1.20342684]]
  
[[ 0.86137023  2.04092751 -2.57888557]
 [ 3.4872083  -1.32344973  4.56819444]]
   
[ 6  6  4  6  6  3  4 10  7  5]
   
3
   
[[5 3 3 3 3]
 [5 3 5 5 3]
 [3 5 5 5 3]]


 union1d remove common elements
 intersect1d prints common elements
